apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app
  labels:
    app: app
spec:
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: "1m"
      - setWeight: 50
      - pause:
          duration: "2m"
      canaryService: app-canary
      stableService: app
      trafficRouting:
        istio:
          virtualService: 
            name: app
            routes:
            - primary 
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: app
      version: v1
  template:
    metadata:
      labels:
        app: app
        version: v1
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      serviceAccountName: app
      containers:
      - name: app
        image: docker.io/cmwylie19/test-argo-rollouts:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "140m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app